# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-15 03:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninja', '0003_remove_ninja_dojo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojo_ninja.Dojo')),
            ],
        ),
        migrations.DeleteModel(
            name='Ninja',
        ),
    ]
