# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-16 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enduser',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='enduser',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
